#!/bin/sh

PREREQ=""
DESCRIPTION="Adding vtsdata to fstab..."
FSTAB=/root/etc/fstab

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

cat >> $FSTAB <<EOF
# filesystem with VTS data, should be on the same USB stick
LABEL=vtsdata	/mnt/vtsdata	ext4	rw,auto	0	1
EOF

log_end_msg
